[package]
name = "gitty-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Standalone CLI for Gitty"

[[bin]]
name = "gitty"
path = "src/main.rs"

[dependencies]
gitty-core = { path = "../gitty-core" }
clap = { version = "4", features = ["derive"] }
anyhow = "1.0.102"
uuid = { version = "1", features = ["v4"] }
time = { version = "0.3.47", features = ["formatting", "serde-well-known"] }

[dev-dependencies]
assert_cmd = "2.2.2"
git2 = { version = "0.21.0", default-features = false }
predicates = "3.1.4"
tempfile = "3.27.0"
